// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: servicios.proto

package serviciosAudio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiciosAudio_ObtenerTipos_FullMethodName         = "/servicios.ServiciosAudio/ObtenerTipos"
	ServiciosAudio_ObtenerAudiosPorTipo_FullMethodName = "/servicios.ServiciosAudio/ObtenerAudiosPorTipo"
	ServiciosAudio_ObtenerMetadata_FullMethodName      = "/servicios.ServiciosAudio/ObtenerMetadata"
)

// ServiciosAudioClient is the client API for ServiciosAudio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiciosAudioClient interface {
	ObtenerTipos(ctx context.Context, in *SolicitudVacia, opts ...grpc.CallOption) (*RespuestaTipos, error)
	ObtenerAudiosPorTipo(ctx context.Context, in *SolicitudPorTipo, opts ...grpc.CallOption) (*RespuestaListaAudios, error)
	ObtenerMetadata(ctx context.Context, in *SolicitudPorId, opts ...grpc.CallOption) (*RespuestaMetadata, error)
}

type serviciosAudioClient struct {
	cc grpc.ClientConnInterface
}

func NewServiciosAudioClient(cc grpc.ClientConnInterface) ServiciosAudioClient {
	return &serviciosAudioClient{cc}
}

func (c *serviciosAudioClient) ObtenerTipos(ctx context.Context, in *SolicitudVacia, opts ...grpc.CallOption) (*RespuestaTipos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaTipos)
	err := c.cc.Invoke(ctx, ServiciosAudio_ObtenerTipos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviciosAudioClient) ObtenerAudiosPorTipo(ctx context.Context, in *SolicitudPorTipo, opts ...grpc.CallOption) (*RespuestaListaAudios, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaListaAudios)
	err := c.cc.Invoke(ctx, ServiciosAudio_ObtenerAudiosPorTipo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviciosAudioClient) ObtenerMetadata(ctx context.Context, in *SolicitudPorId, opts ...grpc.CallOption) (*RespuestaMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaMetadata)
	err := c.cc.Invoke(ctx, ServiciosAudio_ObtenerMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiciosAudioServer is the server API for ServiciosAudio service.
// All implementations must embed UnimplementedServiciosAudioServer
// for forward compatibility.
type ServiciosAudioServer interface {
	ObtenerTipos(context.Context, *SolicitudVacia) (*RespuestaTipos, error)
	ObtenerAudiosPorTipo(context.Context, *SolicitudPorTipo) (*RespuestaListaAudios, error)
	ObtenerMetadata(context.Context, *SolicitudPorId) (*RespuestaMetadata, error)
	mustEmbedUnimplementedServiciosAudioServer()
}

// UnimplementedServiciosAudioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiciosAudioServer struct{}

func (UnimplementedServiciosAudioServer) ObtenerTipos(context.Context, *SolicitudVacia) (*RespuestaTipos, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerTipos not implemented")
}
func (UnimplementedServiciosAudioServer) ObtenerAudiosPorTipo(context.Context, *SolicitudPorTipo) (*RespuestaListaAudios, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerAudiosPorTipo not implemented")
}
func (UnimplementedServiciosAudioServer) ObtenerMetadata(context.Context, *SolicitudPorId) (*RespuestaMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerMetadata not implemented")
}
func (UnimplementedServiciosAudioServer) mustEmbedUnimplementedServiciosAudioServer() {}
func (UnimplementedServiciosAudioServer) testEmbeddedByValue()                        {}

// UnsafeServiciosAudioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiciosAudioServer will
// result in compilation errors.
type UnsafeServiciosAudioServer interface {
	mustEmbedUnimplementedServiciosAudioServer()
}

func RegisterServiciosAudioServer(s grpc.ServiceRegistrar, srv ServiciosAudioServer) {
	// If the following call panics, it indicates UnimplementedServiciosAudioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiciosAudio_ServiceDesc, srv)
}

func _ServiciosAudio_ObtenerTipos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudVacia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiciosAudioServer).ObtenerTipos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiciosAudio_ObtenerTipos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiciosAudioServer).ObtenerTipos(ctx, req.(*SolicitudVacia))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiciosAudio_ObtenerAudiosPorTipo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudPorTipo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiciosAudioServer).ObtenerAudiosPorTipo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiciosAudio_ObtenerAudiosPorTipo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiciosAudioServer).ObtenerAudiosPorTipo(ctx, req.(*SolicitudPorTipo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiciosAudio_ObtenerMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudPorId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiciosAudioServer).ObtenerMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiciosAudio_ObtenerMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiciosAudioServer).ObtenerMetadata(ctx, req.(*SolicitudPorId))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiciosAudio_ServiceDesc is the grpc.ServiceDesc for ServiciosAudio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiciosAudio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.ServiciosAudio",
	HandlerType: (*ServiciosAudioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerTipos",
			Handler:    _ServiciosAudio_ObtenerTipos_Handler,
		},
		{
			MethodName: "ObtenerAudiosPorTipo",
			Handler:    _ServiciosAudio_ObtenerAudiosPorTipo_Handler,
		},
		{
			MethodName: "ObtenerMetadata",
			Handler:    _ServiciosAudio_ObtenerMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicios.proto",
}
