// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: servicios.proto

package serviciosAudio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolicitudVacia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudVacia) Reset() {
	*x = SolicitudVacia{}
	mi := &file_servicios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudVacia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudVacia) ProtoMessage() {}

func (x *SolicitudVacia) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudVacia.ProtoReflect.Descriptor instead.
func (*SolicitudVacia) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{0}
}

type SolicitudPorTipo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTipo        int32                  `protobuf:"varint,1,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudPorTipo) Reset() {
	*x = SolicitudPorTipo{}
	mi := &file_servicios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudPorTipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudPorTipo) ProtoMessage() {}

func (x *SolicitudPorTipo) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudPorTipo.ProtoReflect.Descriptor instead.
func (*SolicitudPorTipo) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{1}
}

func (x *SolicitudPorTipo) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

type SolicitudPorId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudPorId) Reset() {
	*x = SolicitudPorId{}
	mi := &file_servicios_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudPorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudPorId) ProtoMessage() {}

func (x *SolicitudPorId) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudPorId.ProtoReflect.Descriptor instead.
func (*SolicitudPorId) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudPorId) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

type TipoAudioDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TipoAudioDTO) Reset() {
	*x = TipoAudioDTO{}
	mi := &file_servicios_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TipoAudioDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipoAudioDTO) ProtoMessage() {}

func (x *TipoAudioDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipoAudioDTO.ProtoReflect.Descriptor instead.
func (*TipoAudioDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{3}
}

func (x *TipoAudioDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TipoAudioDTO) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type ResumenAudioDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	IdTipo        int32                  `protobuf:"varint,3,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumenAudioDTO) Reset() {
	*x = ResumenAudioDTO{}
	mi := &file_servicios_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumenAudioDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumenAudioDTO) ProtoMessage() {}

func (x *ResumenAudioDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumenAudioDTO.ProtoReflect.Descriptor instead.
func (*ResumenAudioDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{4}
}

func (x *ResumenAudioDTO) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *ResumenAudioDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ResumenAudioDTO) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

type MusicaDTO struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdAudio           int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	Titulo            string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	ArtistaPrincipal  string                 `protobuf:"bytes,3,opt,name=artistaPrincipal,proto3" json:"artistaPrincipal,omitempty"`
	Album             string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	GeneroMusical     string                 `protobuf:"bytes,5,opt,name=generoMusical,proto3" json:"generoMusical,omitempty"`
	SelloDiscografico string                 `protobuf:"bytes,6,opt,name=selloDiscografico,proto3" json:"selloDiscografico,omitempty"`
	AnioLanzamiento   int32                  `protobuf:"varint,7,opt,name=anioLanzamiento,proto3" json:"anioLanzamiento,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MusicaDTO) Reset() {
	*x = MusicaDTO{}
	mi := &file_servicios_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicaDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicaDTO) ProtoMessage() {}

func (x *MusicaDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicaDTO.ProtoReflect.Descriptor instead.
func (*MusicaDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{5}
}

func (x *MusicaDTO) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *MusicaDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *MusicaDTO) GetArtistaPrincipal() string {
	if x != nil {
		return x.ArtistaPrincipal
	}
	return ""
}

func (x *MusicaDTO) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MusicaDTO) GetGeneroMusical() string {
	if x != nil {
		return x.GeneroMusical
	}
	return ""
}

func (x *MusicaDTO) GetSelloDiscografico() string {
	if x != nil {
		return x.SelloDiscografico
	}
	return ""
}

func (x *MusicaDTO) GetAnioLanzamiento() int32 {
	if x != nil {
		return x.AnioLanzamiento
	}
	return 0
}

type PodcastDTO struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IdAudio                int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	TituloPodcast          string                 `protobuf:"bytes,2,opt,name=tituloPodcast,proto3" json:"tituloPodcast,omitempty"`
	TituloEpisodio         string                 `protobuf:"bytes,3,opt,name=tituloEpisodio,proto3" json:"tituloEpisodio,omitempty"`
	Anfitrion              string                 `protobuf:"bytes,4,opt,name=anfitrion,proto3" json:"anfitrion,omitempty"`
	TemporadaEpisodio      string                 `protobuf:"bytes,5,opt,name=temporadaEpisodio,proto3" json:"temporadaEpisodio,omitempty"`
	NotasShow              string                 `protobuf:"bytes,6,opt,name=notasShow,proto3" json:"notasShow,omitempty"`
	ClasificacionContenido string                 `protobuf:"bytes,7,opt,name=clasificacionContenido,proto3" json:"clasificacionContenido,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PodcastDTO) Reset() {
	*x = PodcastDTO{}
	mi := &file_servicios_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodcastDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodcastDTO) ProtoMessage() {}

func (x *PodcastDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodcastDTO.ProtoReflect.Descriptor instead.
func (*PodcastDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{6}
}

func (x *PodcastDTO) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *PodcastDTO) GetTituloPodcast() string {
	if x != nil {
		return x.TituloPodcast
	}
	return ""
}

func (x *PodcastDTO) GetTituloEpisodio() string {
	if x != nil {
		return x.TituloEpisodio
	}
	return ""
}

func (x *PodcastDTO) GetAnfitrion() string {
	if x != nil {
		return x.Anfitrion
	}
	return ""
}

func (x *PodcastDTO) GetTemporadaEpisodio() string {
	if x != nil {
		return x.TemporadaEpisodio
	}
	return ""
}

func (x *PodcastDTO) GetNotasShow() string {
	if x != nil {
		return x.NotasShow
	}
	return ""
}

func (x *PodcastDTO) GetClasificacionContenido() string {
	if x != nil {
		return x.ClasificacionContenido
	}
	return ""
}

type AudiolibroDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor         string                 `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	Narrador      string                 `protobuf:"bytes,4,opt,name=narrador,proto3" json:"narrador,omitempty"`
	Editorial     string                 `protobuf:"bytes,5,opt,name=editorial,proto3" json:"editorial,omitempty"`
	Isbn          string                 `protobuf:"bytes,6,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Capitulo      string                 `protobuf:"bytes,7,opt,name=capitulo,proto3" json:"capitulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiolibroDTO) Reset() {
	*x = AudiolibroDTO{}
	mi := &file_servicios_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiolibroDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiolibroDTO) ProtoMessage() {}

func (x *AudiolibroDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiolibroDTO.ProtoReflect.Descriptor instead.
func (*AudiolibroDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{7}
}

func (x *AudiolibroDTO) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *AudiolibroDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *AudiolibroDTO) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *AudiolibroDTO) GetNarrador() string {
	if x != nil {
		return x.Narrador
	}
	return ""
}

func (x *AudiolibroDTO) GetEditorial() string {
	if x != nil {
		return x.Editorial
	}
	return ""
}

func (x *AudiolibroDTO) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *AudiolibroDTO) GetCapitulo() string {
	if x != nil {
		return x.Capitulo
	}
	return ""
}

type RuidoBlancoDTO struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IdAudio             int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	TipoSonido          string                 `protobuf:"bytes,2,opt,name=tipoSonido,proto3" json:"tipoSonido,omitempty"`
	FuenteAudio         string                 `protobuf:"bytes,3,opt,name=fuenteAudio,proto3" json:"fuenteAudio,omitempty"`
	UsoSugerido         string                 `protobuf:"bytes,4,opt,name=usoSugerido,proto3" json:"usoSugerido,omitempty"`
	ProveedorContenido  string                 `protobuf:"bytes,5,opt,name=proveedorContenido,proto3" json:"proveedorContenido,omitempty"`
	DuracionBucle       int32                  `protobuf:"varint,6,opt,name=duracionBucle,proto3" json:"duracionBucle,omitempty"`
	FrecuenciaDominante string                 `protobuf:"bytes,7,opt,name=frecuenciaDominante,proto3" json:"frecuenciaDominante,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuidoBlancoDTO) Reset() {
	*x = RuidoBlancoDTO{}
	mi := &file_servicios_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuidoBlancoDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuidoBlancoDTO) ProtoMessage() {}

func (x *RuidoBlancoDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuidoBlancoDTO.ProtoReflect.Descriptor instead.
func (*RuidoBlancoDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{8}
}

func (x *RuidoBlancoDTO) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *RuidoBlancoDTO) GetTipoSonido() string {
	if x != nil {
		return x.TipoSonido
	}
	return ""
}

func (x *RuidoBlancoDTO) GetFuenteAudio() string {
	if x != nil {
		return x.FuenteAudio
	}
	return ""
}

func (x *RuidoBlancoDTO) GetUsoSugerido() string {
	if x != nil {
		return x.UsoSugerido
	}
	return ""
}

func (x *RuidoBlancoDTO) GetProveedorContenido() string {
	if x != nil {
		return x.ProveedorContenido
	}
	return ""
}

func (x *RuidoBlancoDTO) GetDuracionBucle() int32 {
	if x != nil {
		return x.DuracionBucle
	}
	return 0
}

func (x *RuidoBlancoDTO) GetFrecuenciaDominante() string {
	if x != nil {
		return x.FrecuenciaDominante
	}
	return ""
}

type RespuestaBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codigo        int32                  `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaBase) Reset() {
	*x = RespuestaBase{}
	mi := &file_servicios_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaBase) ProtoMessage() {}

func (x *RespuestaBase) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaBase.ProtoReflect.Descriptor instead.
func (*RespuestaBase) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{9}
}

func (x *RespuestaBase) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaBase) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type RespuestaTipos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        *RespuestaBase         `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Tipos         []*TipoAudioDTO        `protobuf:"bytes,2,rep,name=tipos,proto3" json:"tipos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaTipos) Reset() {
	*x = RespuestaTipos{}
	mi := &file_servicios_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaTipos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaTipos) ProtoMessage() {}

func (x *RespuestaTipos) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaTipos.ProtoReflect.Descriptor instead.
func (*RespuestaTipos) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{10}
}

func (x *RespuestaTipos) GetEstado() *RespuestaBase {
	if x != nil {
		return x.Estado
	}
	return nil
}

func (x *RespuestaTipos) GetTipos() []*TipoAudioDTO {
	if x != nil {
		return x.Tipos
	}
	return nil
}

type RespuestaListaAudios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        *RespuestaBase         `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Audios        []*ResumenAudioDTO     `protobuf:"bytes,2,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaListaAudios) Reset() {
	*x = RespuestaListaAudios{}
	mi := &file_servicios_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaListaAudios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaListaAudios) ProtoMessage() {}

func (x *RespuestaListaAudios) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaListaAudios.ProtoReflect.Descriptor instead.
func (*RespuestaListaAudios) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{11}
}

func (x *RespuestaListaAudios) GetEstado() *RespuestaBase {
	if x != nil {
		return x.Estado
	}
	return nil
}

func (x *RespuestaListaAudios) GetAudios() []*ResumenAudioDTO {
	if x != nil {
		return x.Audios
	}
	return nil
}

type RespuestaMetadata struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Estado *RespuestaBase         `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	// Types that are valid to be assigned to Metadato:
	//
	//	*RespuestaMetadata_Musica
	//	*RespuestaMetadata_Podcast
	//	*RespuestaMetadata_Audiolibro
	//	*RespuestaMetadata_RuidoBlanco
	Metadato      isRespuestaMetadata_Metadato `protobuf_oneof:"metadato"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaMetadata) Reset() {
	*x = RespuestaMetadata{}
	mi := &file_servicios_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaMetadata) ProtoMessage() {}

func (x *RespuestaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaMetadata.ProtoReflect.Descriptor instead.
func (*RespuestaMetadata) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{12}
}

func (x *RespuestaMetadata) GetEstado() *RespuestaBase {
	if x != nil {
		return x.Estado
	}
	return nil
}

func (x *RespuestaMetadata) GetMetadato() isRespuestaMetadata_Metadato {
	if x != nil {
		return x.Metadato
	}
	return nil
}

func (x *RespuestaMetadata) GetMusica() *MusicaDTO {
	if x != nil {
		if x, ok := x.Metadato.(*RespuestaMetadata_Musica); ok {
			return x.Musica
		}
	}
	return nil
}

func (x *RespuestaMetadata) GetPodcast() *PodcastDTO {
	if x != nil {
		if x, ok := x.Metadato.(*RespuestaMetadata_Podcast); ok {
			return x.Podcast
		}
	}
	return nil
}

func (x *RespuestaMetadata) GetAudiolibro() *AudiolibroDTO {
	if x != nil {
		if x, ok := x.Metadato.(*RespuestaMetadata_Audiolibro); ok {
			return x.Audiolibro
		}
	}
	return nil
}

func (x *RespuestaMetadata) GetRuidoBlanco() *RuidoBlancoDTO {
	if x != nil {
		if x, ok := x.Metadato.(*RespuestaMetadata_RuidoBlanco); ok {
			return x.RuidoBlanco
		}
	}
	return nil
}

type isRespuestaMetadata_Metadato interface {
	isRespuestaMetadata_Metadato()
}

type RespuestaMetadata_Musica struct {
	Musica *MusicaDTO `protobuf:"bytes,2,opt,name=musica,proto3,oneof"`
}

type RespuestaMetadata_Podcast struct {
	Podcast *PodcastDTO `protobuf:"bytes,3,opt,name=podcast,proto3,oneof"`
}

type RespuestaMetadata_Audiolibro struct {
	Audiolibro *AudiolibroDTO `protobuf:"bytes,4,opt,name=audiolibro,proto3,oneof"`
}

type RespuestaMetadata_RuidoBlanco struct {
	RuidoBlanco *RuidoBlancoDTO `protobuf:"bytes,5,opt,name=ruidoBlanco,proto3,oneof"`
}

func (*RespuestaMetadata_Musica) isRespuestaMetadata_Metadato() {}

func (*RespuestaMetadata_Podcast) isRespuestaMetadata_Metadato() {}

func (*RespuestaMetadata_Audiolibro) isRespuestaMetadata_Metadato() {}

func (*RespuestaMetadata_RuidoBlanco) isRespuestaMetadata_Metadato() {}

var File_servicios_proto protoreflect.FileDescriptor

const file_servicios_proto_rawDesc = "" +
	"\n" +
	"\x0fservicios.proto\x12\tservicios\"\x10\n" +
	"\x0eSolicitudVacia\"*\n" +
	"\x10SolicitudPorTipo\x12\x16\n" +
	"\x06idTipo\x18\x01 \x01(\x05R\x06idTipo\"*\n" +
	"\x0eSolicitudPorId\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\"6\n" +
	"\fTipoAudioDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"[\n" +
	"\x0fResumenAudioDTO\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x16\n" +
	"\x06idTipo\x18\x03 \x01(\x05R\x06idTipo\"\xfd\x01\n" +
	"\tMusicaDTO\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12*\n" +
	"\x10artistaPrincipal\x18\x03 \x01(\tR\x10artistaPrincipal\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12$\n" +
	"\rgeneroMusical\x18\x05 \x01(\tR\rgeneroMusical\x12,\n" +
	"\x11selloDiscografico\x18\x06 \x01(\tR\x11selloDiscografico\x12(\n" +
	"\x0fanioLanzamiento\x18\a \x01(\x05R\x0fanioLanzamiento\"\x96\x02\n" +
	"\n" +
	"PodcastDTO\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\x12$\n" +
	"\rtituloPodcast\x18\x02 \x01(\tR\rtituloPodcast\x12&\n" +
	"\x0etituloEpisodio\x18\x03 \x01(\tR\x0etituloEpisodio\x12\x1c\n" +
	"\tanfitrion\x18\x04 \x01(\tR\tanfitrion\x12,\n" +
	"\x11temporadaEpisodio\x18\x05 \x01(\tR\x11temporadaEpisodio\x12\x1c\n" +
	"\tnotasShow\x18\x06 \x01(\tR\tnotasShow\x126\n" +
	"\x16clasificacionContenido\x18\a \x01(\tR\x16clasificacionContenido\"\xc1\x01\n" +
	"\rAudiolibroDTO\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x03 \x01(\tR\x05autor\x12\x1a\n" +
	"\bnarrador\x18\x04 \x01(\tR\bnarrador\x12\x1c\n" +
	"\teditorial\x18\x05 \x01(\tR\teditorial\x12\x12\n" +
	"\x04isbn\x18\x06 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcapitulo\x18\a \x01(\tR\bcapitulo\"\x96\x02\n" +
	"\x0eRuidoBlancoDTO\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\x12\x1e\n" +
	"\n" +
	"tipoSonido\x18\x02 \x01(\tR\n" +
	"tipoSonido\x12 \n" +
	"\vfuenteAudio\x18\x03 \x01(\tR\vfuenteAudio\x12 \n" +
	"\vusoSugerido\x18\x04 \x01(\tR\vusoSugerido\x12.\n" +
	"\x12proveedorContenido\x18\x05 \x01(\tR\x12proveedorContenido\x12$\n" +
	"\rduracionBucle\x18\x06 \x01(\x05R\rduracionBucle\x120\n" +
	"\x13frecuenciaDominante\x18\a \x01(\tR\x13frecuenciaDominante\"A\n" +
	"\rRespuestaBase\x12\x16\n" +
	"\x06codigo\x18\x01 \x01(\x05R\x06codigo\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"q\n" +
	"\x0eRespuestaTipos\x120\n" +
	"\x06estado\x18\x01 \x01(\v2\x18.servicios.RespuestaBaseR\x06estado\x12-\n" +
	"\x05tipos\x18\x02 \x03(\v2\x17.servicios.TipoAudioDTOR\x05tipos\"|\n" +
	"\x14RespuestaListaAudios\x120\n" +
	"\x06estado\x18\x01 \x01(\v2\x18.servicios.RespuestaBaseR\x06estado\x122\n" +
	"\x06audios\x18\x02 \x03(\v2\x1a.servicios.ResumenAudioDTOR\x06audios\"\xaf\x02\n" +
	"\x11RespuestaMetadata\x120\n" +
	"\x06estado\x18\x01 \x01(\v2\x18.servicios.RespuestaBaseR\x06estado\x12.\n" +
	"\x06musica\x18\x02 \x01(\v2\x14.servicios.MusicaDTOH\x00R\x06musica\x121\n" +
	"\apodcast\x18\x03 \x01(\v2\x15.servicios.PodcastDTOH\x00R\apodcast\x12:\n" +
	"\n" +
	"audiolibro\x18\x04 \x01(\v2\x18.servicios.AudiolibroDTOH\x00R\n" +
	"audiolibro\x12=\n" +
	"\vruidoBlanco\x18\x05 \x01(\v2\x19.servicios.RuidoBlancoDTOH\x00R\vruidoBlancoB\n" +
	"\n" +
	"\bmetadato2\xf8\x01\n" +
	"\x0eServiciosAudio\x12D\n" +
	"\fObtenerTipos\x12\x19.servicios.SolicitudVacia\x1a\x19.servicios.RespuestaTipos\x12T\n" +
	"\x14ObtenerAudiosPorTipo\x12\x1b.servicios.SolicitudPorTipo\x1a\x1f.servicios.RespuestaListaAudios\x12J\n" +
	"\x0fObtenerMetadata\x12\x19.servicios.SolicitudPorId\x1a\x1c.servicios.RespuestaMetadataB\x11Z\x0f/serviciosAudiob\x06proto3"

var (
	file_servicios_proto_rawDescOnce sync.Once
	file_servicios_proto_rawDescData []byte
)

func file_servicios_proto_rawDescGZIP() []byte {
	file_servicios_proto_rawDescOnce.Do(func() {
		file_servicios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)))
	})
	return file_servicios_proto_rawDescData
}

var file_servicios_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_servicios_proto_goTypes = []any{
	(*SolicitudVacia)(nil),       // 0: servicios.SolicitudVacia
	(*SolicitudPorTipo)(nil),     // 1: servicios.SolicitudPorTipo
	(*SolicitudPorId)(nil),       // 2: servicios.SolicitudPorId
	(*TipoAudioDTO)(nil),         // 3: servicios.TipoAudioDTO
	(*ResumenAudioDTO)(nil),      // 4: servicios.ResumenAudioDTO
	(*MusicaDTO)(nil),            // 5: servicios.MusicaDTO
	(*PodcastDTO)(nil),           // 6: servicios.PodcastDTO
	(*AudiolibroDTO)(nil),        // 7: servicios.AudiolibroDTO
	(*RuidoBlancoDTO)(nil),       // 8: servicios.RuidoBlancoDTO
	(*RespuestaBase)(nil),        // 9: servicios.RespuestaBase
	(*RespuestaTipos)(nil),       // 10: servicios.RespuestaTipos
	(*RespuestaListaAudios)(nil), // 11: servicios.RespuestaListaAudios
	(*RespuestaMetadata)(nil),    // 12: servicios.RespuestaMetadata
}
var file_servicios_proto_depIdxs = []int32{
	9,  // 0: servicios.RespuestaTipos.estado:type_name -> servicios.RespuestaBase
	3,  // 1: servicios.RespuestaTipos.tipos:type_name -> servicios.TipoAudioDTO
	9,  // 2: servicios.RespuestaListaAudios.estado:type_name -> servicios.RespuestaBase
	4,  // 3: servicios.RespuestaListaAudios.audios:type_name -> servicios.ResumenAudioDTO
	9,  // 4: servicios.RespuestaMetadata.estado:type_name -> servicios.RespuestaBase
	5,  // 5: servicios.RespuestaMetadata.musica:type_name -> servicios.MusicaDTO
	6,  // 6: servicios.RespuestaMetadata.podcast:type_name -> servicios.PodcastDTO
	7,  // 7: servicios.RespuestaMetadata.audiolibro:type_name -> servicios.AudiolibroDTO
	8,  // 8: servicios.RespuestaMetadata.ruidoBlanco:type_name -> servicios.RuidoBlancoDTO
	0,  // 9: servicios.ServiciosAudio.ObtenerTipos:input_type -> servicios.SolicitudVacia
	1,  // 10: servicios.ServiciosAudio.ObtenerAudiosPorTipo:input_type -> servicios.SolicitudPorTipo
	2,  // 11: servicios.ServiciosAudio.ObtenerMetadata:input_type -> servicios.SolicitudPorId
	10, // 12: servicios.ServiciosAudio.ObtenerTipos:output_type -> servicios.RespuestaTipos
	11, // 13: servicios.ServiciosAudio.ObtenerAudiosPorTipo:output_type -> servicios.RespuestaListaAudios
	12, // 14: servicios.ServiciosAudio.ObtenerMetadata:output_type -> servicios.RespuestaMetadata
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_servicios_proto_init() }
func file_servicios_proto_init() {
	if File_servicios_proto != nil {
		return
	}
	file_servicios_proto_msgTypes[12].OneofWrappers = []any{
		(*RespuestaMetadata_Musica)(nil),
		(*RespuestaMetadata_Podcast)(nil),
		(*RespuestaMetadata_Audiolibro)(nil),
		(*RespuestaMetadata_RuidoBlanco)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicios_proto_goTypes,
		DependencyIndexes: file_servicios_proto_depIdxs,
		MessageInfos:      file_servicios_proto_msgTypes,
	}.Build()
	File_servicios_proto = out.File
	file_servicios_proto_goTypes = nil
	file_servicios_proto_depIdxs = nil
}
